name: Hello

on:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Hello world
      run: echo Hello, world!
    - name: test
      env: 
        EVENT_NAME: ${{ github.event_name }}
      run: echo "$EVENT_NAME"
